format = """\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_metrics\
$fill\
$cmd_duration $jobs $time\
$line_break\
$character"""

[fill]
symbol = " "

[directory]
style = "blue"
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[#](purple)"
error_symbol = "[#](red)"
vicmd_symbol = "[#](green)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style)"
style = "bright-black"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[time]
disabled = false
style = "bold-white"
format = "[$time]($style)"

